### PR TITLE
fix(feature): toggle correctly display for list and update feature

### PR DESCRIPTION
**Pull request by corinnekrych**
Fixes https://github.com/Unleash/unleash-frontend/issues/125

### CODE REVIEW

**Comment by xcoulon** [comment]
I tried it locally with the `npm run start:heroku` command to test it against the backend running on Heroku and I could not reproduce the bug anymore.

**Comment by corinnekrych** [comment]
@ivarconr are you ok to merge that one? this is a fix for an annoying bug where all features in feature list are displayed with disabled toggle.

**Comment by ivarconr** [comment]
yes indeed! 

Maybe time to do a release of `unleash-frontend` soon, in order to bring these new goodies you have implemented to the ppls?

**Comment by corinnekrych** [comment]
@ivarconr +1 on doing a release!

**Comment by ivarconr** [comment]
@corinnekrych unleash-frontend released as `3.0.1` and unleash-server released as  `3.0.2`.

**Comment by corinnekrych** [comment]
🎉 
Thanks @ivarconr I'll use the release then!

**Pull request merged**
