### PR TITLE
fix: babel-preset-env

### PR DESCRIPTION
**Pull request by luanraithz**
#151 
Removed deprecated babel config
Runned link fix

### CODE REVIEW

**Comment by ivarconr** [comment]
Thanks for looking at this. I'm a bit busy the next couple of days but will look in to it soon.

Do you understand why one of the snapshot tests fail?

**Comment by luanraithz** [comment]
Sorry, I didn't see this failing test, the problem seems to happen because the [updateConfig function](https://github.com/luanraithz/unleash-frontend/blob/master/src/store/ui-config/index.js#L28), which updates local storage, so the next test will have something [here](https://github.com/luanraithz/unleash-frontend/blob/master/src/store/ui-config/index.js#L20).
If you run only the `should only update headerBackground` test, it works (at least on my machine).
I just don't know if it was a breaking change in the [new jest version](https://github.com/luanraithz/unleash-frontend/blob/master/package.json#L65) or something else.

What should I do? Add a beforeEach to clear localstorage?

**Comment by ivarconr** [comment]
Ahh, good catch. UI options is stored locally as they seldom changes and thus is stupid to must fetch them from server. 

> Add a beforeEach to clear localstorage?

Sounds like a good approach.

**Comment by luanraithz** [comment]
@ivarconr did it

**Pull request merged**
