### PR TITLE
chore(workflows): update with new branch names

### PR DESCRIPTION
**Pull request by thomasheartman**

### CODE REVIEW

**Comment by thomasheartman** [comment]
[Rename GitHub default branches from master to main](https://trello.com/c/Ey6olr8s/669-rename-github-default-branches-from-master-to-main)

**Review by FredrikOseberg — APPROVED** [review]

**Comment by thomasheartman** [comment]
@FredrikOseberg It might be best to rename the branch before merging this (or put both main and master in the `branches` property). Should we go ahead and do that now?

**Comment by FredrikOseberg** [comment]
> @FredrikOseberg It might be best to rename the branch before merging this (or put both main and master in the `branches` property). Should we go ahead and do that now?

Let's hold off until we've merged some of the outstanding PRs here. I think it will be beneficial to get on top of things before we rename here. I'll keep you updated.

**Comment by thomasheartman** [comment]
As discussed, I'll merge this in as soon as the pipeline is done.

**Pull request merged**
