### PR TITLE
make link to feature toggle span full width of list

### PR DESCRIPTION
**Pull request by vsandvold**
Added 100% width to feature link + some minor refactoring making use of mdl css classes.

### CODE REVIEW

**Comment by sveisvei** [comment]
lgtm

**Comment by ivarconr** [comment]
Cool, and welcome to the party @vsandvold 🎉

**Comment by sveisvei** [comment]
Very long names with many strategies(> 3) does create some issues here @vsandvold. Not sure how we can solve this in a nice way.

**Comment by sveisvei** [comment]
https://github.com/Unleash/unleash-frontend/pull/35 might help with the chips at least

**Comment by vsandvold** [comment]
Have you considered two lines per feature item (using `mdl-list__item--two-line`)? That would give more space for strategies. I can set up a PR with a suggestion if you like.

**Pull request merged**
