### PR TITLE
feat: add edit and create user screen (NEW)

### PR DESCRIPTION
**Pull request by ykhedher**

### CODE REVIEW

**Comment by ykhedher** [comment]
[Create screen - User](https://trello.com/c/UIU2K0Wo/683-create-screen-user)

**Review by FredrikOseberg — APPROVED** [review]
LGTM once we change the naming of the component and update the docs links.

**Comment by ykhedher** [comment]
> Hm. I see we have now lost the ability to copy the token. We need to have this in case email configuration is not set up. I think we should have that as a confirm screen after we create the user.

I forgot about that. I was going to ask about it, but I think I forgot since it is 15 days ago lol

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Pull request merged**
