### PR TITLE
feat:new toggle screen view

### PR DESCRIPTION
**Pull request by ykhedher**
Screen Shot 2021-12-03 at 9 24 54 AM

### CODE REVIEW

**Comment by FredrikOseberg** [comment]
togglelist

Looks like we missed an edit button. Also, seems like delete tag is gone. Not just, here but also on the master. Might be unrelated, but we need to resolve.

**Comment by ykhedher** [comment]
[Make it more clear when you are on a project, and when you are on a toggle.](https://trello.com/c/P4hTRTjb/614-make-it-more-clear-when-you-are-on-a-project-and-when-you-are-on-a-toggle)

**Comment by ykhedher** [comment]
> Skjermbilde 2021-12-06 kl 09 23 59
> 
> Looks like we missed an edit button. Also, seems like delete tag is gone. Not just, here but also on the master. Might be unrelated, but we need to resolve.

Fixed ✅

**Comment by ykhedher** [comment]
[Switch Toggle execution to Feature toggle execution in the feature toggle view.](https://trello.com/c/NlPCJegy/645-switch-toggle-execution-to-feature-toggle-execution-in-the-feature-toggle-view)

**Comment by ykhedher** [comment]
[Pie chart, test different models. Currently looks like it has data.](https://trello.com/c/MSd4bZbD/612-pie-chart-test-different-models-currently-looks-like-it-has-data)

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Review by ivarconr — APPROVED** [review]

**Review by ivarconr — APPROVED** [review]

**Comment by ykhedher** [comment]
[Add strategy icons to toggle overview and change the metrics text when no strategies are enabled.](https://trello.com/c/a4osvy2j/622-add-strategy-icons-to-toggle-overview-and-change-the-metrics-text-when-no-strategies-are-enabled)

**Pull request merged**
