### PR TITLE
fix: remove create-toggle2 from breadcrumb menu

### PR DESCRIPTION
**Pull request by ykhedher**
Screen Shot 2022-01-07 at 7 19 45 AM

### CODE REVIEW

**Comment by ykhedher** [comment]
[Fix breadcrumbnav to remove create-toggle2](https://trello.com/c/oGoiyXCu/709-fix-breadcrumbnav-to-remove-create-toggle2)

**Review by FredrikOseberg — APPROVED** [review]
LGTM. Though we can now change the route from create-toggle2 to create-toggle.

**Comment by ykhedher** [comment]
> LGTM. Though we can now change the route from create-toggle2 to create-toggle.

@FredrikOseberg I will update this pr to change create-toggle2 to create-toggle

**Review by FredrikOseberg — APPROVED** [review]
LGTM. As long as we are 100% sure all links pointing to this has been updated.

**Review by ivarconr — APPROVED** [review]
looks good, would probably have a redirect from create-toggle2 => create-toggle if possible.

**Comment by ykhedher** [comment]
> looks good, would probably have a redirect from create-toggle2 => create-toggle if possible.

@ivarconr I think there's no need for a redirect since we updated all the links containing `create-toggle2` using VS code search.

**Pull request merged**
